export const ids = {
  user: (i: number) => `user_${i}`,
  session: (i: number) => `session_${i}`,
  account: (i: number) => `account_${i}`,
  verification: (i: number) => `verification_${i}`,
  org: (i: number) => `org_${i}`,
  roleBinding: (i: number) => `role_binding_${i}`,
  event: (i: number) => `event_${i}`,
  eventSession: (eventIndex: number, sessionIndex: number) =>
    `event_session_${eventIndex}_${sessionIndex}`,
  gate: (eventIndex: number, gateIndex: number) => `gate_${eventIndex}_${gateIndex}`,
  gateStaffAssignment: (i: number) => `gate_staff_assignment_${i}`,
  gateTicketClassAccess: (i: number) => `gate_ticket_access_${i}`,
  ticketClass: (eventIndex: number, tier: string) =>
    `ticket_class_${eventIndex}_${tier.toLowerCase()}`,
  reservation: (i: number) => `reservation_${i}`,
  reservationItem: (reservationIndex: number, itemIndex: number) =>
    `reservation_item_${reservationIndex}_${itemIndex}`,
  waitlist: (i: number) => `waitlist_${i}`,
  order: (i: number) => `order_${i}`,
  paymentAttempt: (orderIndex: number, attemptIndex: number) =>
    `payment_attempt_${orderIndex}_${attemptIndex}`,
  refund: (i: number) => `refund_${i}`,
  ticket: (i: number) => `ticket_${i}`,
  transfer: (i: number) => `transfer_${i}`,
  checkIn: (i: number) => `checkin_${i}`,
  feedback: (i: number) => `feedback_${i}`,
  abuse: (i: number) => `abuse_${i}`,
  risk: (i: number) => `risk_${i}`,
  settlement: (i: number) => `settlement_${i}`,
  payout: (i: number) => `payout_${i}`,
  audit: (i: number) => `audit_${i}`,
  dataExport: (i: number) => `data_export_${i}`,
  policyAcceptance: (i: number) => `policy_acceptance_${i}`,
  dataDeletion: (i: number) => `data_deletion_${i}`,
  webhookEndpoint: (i: number) => `webhook_endpoint_${i}`,
  webhookOutbox: (i: number) => `webhook_outbox_${i}`,
  webhookDeliveryAttempt: (i: number) => `webhook_delivery_attempt_${i}`,
  inboundProviderEvent: (i: number) => `inbound_provider_event_${i}`,
  notificationPreference: (i: number) => `notification_preference_${i}`,
  notificationDelivery: (i: number) => `notification_delivery_${i}`,
  notificationAttempt: (i: number) => `notification_attempt_${i}`,
  qrToken: (i: number) => `qr_token_${i}`,
  idempotency: (scope: string, i: number) => `${scope}_idempotency_${i}`,
  providerEvent: (provider: string, i: number) => `${provider}_event_${i}`,
  transferRef: (i: number) => `transfer_ref_${i}`,
};

export type IdFactory = typeof ids;
